# **Mi primer Jupyter Notebook en Google Colab...**

Vamos a mantener la misma estructura en todas las tareas: la primera celda va a ser para marcar la tarea con su nombre

In [ ]:
#tad1.ipynb
#Nombre:

python es ampliamente usado gracias a su estructura modular; únicamente cargamos los modulos (scripts o funciones prediseñadas) que vamos a usar...

In [ ]:
#importar los modulos que vamos a usar

import numpy as np

In [ ]:
#definir variables
arrayA=[1,2,3,4]
print(A)

arrayB=np.zeros(10)
print(arrayB)

[1, 2, 3]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arrayC=np.matrix('1 2; 3 4')
arrayD=np.matrix([[1, 2], [3, 4]])
arrayE=np.zeros((2,2))

print(arrayC)
print(arrayD)
print(arrayE)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[0. 0.]
 [0. 0.]]


# tarea - primera parte
¿Se pueden sumar vectores y matrices? ¿Se pueden multiplicar? *Ejecute cada una de las siguientes operaciones en una celda independiente



1.   sumar los arreglos A y B
2.   multiplicar arreglos A y B
3.   sumar los arreglos C y D
4.   multiplicar arreglos C y D
5.   sumar los arreglos A y C
6.   multiplicar arreglos A y C




In [ ]:
arrayF = np.arange(0, 1.1, 0.1)
arrayG = np.linspace(0,2,9)

print(arrayF)
print(arrayG)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# tarea - segunda parte
Ahora vamos a usar la ley de Hooke generalizada (ecuación de la última diapositiva de la clase 2) para estimar el tensor de esfuerzos "S", correspondiente al estado de esfuerzos en un punto, dado por el tesor de deformaciones "Ε" que se muestra a continuación.

*Ejecute cada una de las operaciones (definir las variables y hacer el/los cálculo necesarios) en una celda independiente

**Asuma que los valores del tensor de coeficientes elásticos "C" son todos iguales a 1

E=
\begin{bmatrix}
-4 & 4 & 3\\
4 & -2 & -2\\
3 & -2 & -3
\end{bmatrix}


# tarea - tercera parte
¿cuál es el valor de la compoennte S23 del tensor de esfuerzos?

Respuesta tercera parte: